#!/usr/bin/env bash
# claude-switch — Toggle Claude Code between proxy and official auth modes
# Install to ~/.local/bin/claude-switch via install.sh

set -euo pipefail

CONFIG_DIR="$HOME/.config/claude-switch"
CONFIG_FILE="$CONFIG_DIR/config"
ENV_FILE="$CONFIG_DIR/env"
ACTIVE_FILE="$CONFIG_DIR/active"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
# Claude Code config — current location is ~/.claude.json (home root);
# legacy location is ~/.claude/claude.json.  We handle both.
CLAUDE_JSON="$HOME/.claude.json"
CLAUDE_JSON_LEGACY="$HOME/.claude/claude.json"
STASHED_OAUTH="$CONFIG_DIR/oauth.json.bak"

# Ensure config directory exists
mkdir -p "$CONFIG_DIR"

# Create default config if missing
if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" <<'DEFAULTS'
PROXY_BASE_URL=http://YOUR_PROXY_HOST:11212/api/anthropic
PROXY_API_KEY=YOUR_API_KEY_HERE
DEFAULTS
    echo "Created default config at $CONFIG_FILE — edit it with your proxy details"
fi

# Load config (safe key=value parsing, no arbitrary execution)
# || true prevents set -e from exiting when grep finds no match
PROXY_BASE_URL=$(grep '^PROXY_BASE_URL=' "$CONFIG_FILE" | head -1 | cut -d= -f2- || true)
PROXY_API_KEY=$(grep '^PROXY_API_KEY=' "$CONFIG_FILE" | head -1 | cut -d= -f2- || true)

usage() {
    cat <<EOF
Usage: claude-switch <command> [options]

Commands:
  proxy [URL [API_KEY]]   Switch to proxy mode
  official                Switch to official Claude AI OAuth
  status                  Show current auth mode
  config                  Show config file path for editing

If URL or API_KEY are provided with 'proxy', they are saved to the config file
for future use. Otherwise the saved values are used.

Examples:
  claude-switch proxy                                          # Use saved config
  claude-switch proxy http://myhost:8080/api/anthropic         # Update URL
  claude-switch proxy http://myhost:8080/api/anthropic sk-key  # Update URL + key
  claude-switch official                                       # Switch to OAuth
  claude-switch status                                         # Show current mode

Config: $CONFIG_FILE
EOF
    exit 1
}

# Validate that proxy config is usable (not still placeholder values)
validate_proxy_config() {
    local url="$1" key="$2"
    local valid=true

    if [ -z "$url" ] || [[ "$url" == *"YOUR_PROXY_HOST"* ]]; then
        echo "ERROR: PROXY_BASE_URL is not configured." >&2
        valid=false
    fi
    if [ -z "$key" ] || [ "$key" = "YOUR_API_KEY_HERE" ]; then
        echo "ERROR: PROXY_API_KEY is not configured." >&2
        valid=false
    fi

    if [ "$valid" = false ]; then
        echo "" >&2
        echo "Edit your config: $CONFIG_FILE" >&2
        echo "Or pass values directly: claude-switch proxy <URL> <API_KEY>" >&2
        return 1
    fi
}

# Update a key=value in the config file
update_config() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$CONFIG_FILE"; then
        # Replace existing line — use a delimiter unlikely to appear in URLs
        sed -i.tmp "s|^${key}=.*|${key}=${value}|" "$CONFIG_FILE"
        rm -f "$CONFIG_FILE.tmp"
    else
        echo "${key}=${value}" >> "$CONFIG_FILE"
    fi
}

# Read or initialize claude settings.json
read_settings() {
    if [ -f "$CLAUDE_SETTINGS" ]; then
        cat "$CLAUDE_SETTINGS"
    else
        echo '{}'
    fi
}

# Write settings.json with or without apiBaseUrl
write_settings() {
    local mode="$1"
    local settings

    mkdir -p "$(dirname "$CLAUDE_SETTINGS")"
    settings=$(read_settings)

    if ! command -v python3 &>/dev/null; then
        echo "ERROR: python3 is required but not found" >&2
        return 1
    fi

    if [ "$mode" = "proxy" ]; then
        # Add/update apiBaseUrl (pass URL via env to avoid injection)
        if ! echo "$settings" | PROXY_URL="$PROXY_BASE_URL" python3 -c "
import sys, json, os
d = json.load(sys.stdin)
d['apiBaseUrl'] = os.environ['PROXY_URL']
json.dump(d, sys.stdout, indent=2)
print()
" > "$CLAUDE_SETTINGS.tmp"; then
            echo "ERROR: Failed to parse $CLAUDE_SETTINGS — skipping settings update" >&2
            rm -f "$CLAUDE_SETTINGS.tmp"
            return 1
        fi
    else
        # Remove apiBaseUrl
        if ! echo "$settings" | python3 -c "
import sys, json
d = json.load(sys.stdin)
d.pop('apiBaseUrl', None)
json.dump(d, sys.stdout, indent=2)
print()
" > "$CLAUDE_SETTINGS.tmp"; then
            echo "ERROR: Failed to parse $CLAUDE_SETTINGS — skipping settings update" >&2
            rm -f "$CLAUDE_SETTINGS.tmp"
            return 1
        fi
    fi

    mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
}

# Write the sourceable env file
write_env() {
    local mode="$1"

    if [ "$mode" = "proxy" ]; then
        cat > "$ENV_FILE" <<EOF
# Claude Code auth — proxy mode (auto-generated by claude-switch)
export ANTHROPIC_BASE_URL="$PROXY_BASE_URL"
export ANTHROPIC_API_KEY="$PROXY_API_KEY"
EOF
    else
        cat > "$ENV_FILE" <<'EOF'
# Claude Code auth — official mode (auto-generated by claude-switch)
unset ANTHROPIC_BASE_URL
unset ANTHROPIC_API_KEY
EOF
    fi
}

# Stash OAuth account from claude config to avoid auth conflict in proxy mode.
# Claude Code stores its OAuth token in the "oauthAccount" key.
# If both oauthAccount and ANTHROPIC_API_KEY exist, Claude shows an
# "Auth conflict" error.  We extract and remove the key for proxy mode,
# and restore it when switching back to official.
#
# Handles both ~/.claude.json (current) and ~/.claude/claude.json (legacy).
stash_oauth() {
    local files_to_strip=()
    for f in "$CLAUDE_JSON" "$CLAUDE_JSON_LEGACY"; do
        [ -f "$f" ] && files_to_strip+=("$f")
    done
    if [ ${#files_to_strip[@]} -eq 0 ]; then
        return
    fi

    # Extract oauthAccount from the first file that has it (for backup),
    # then strip oauthAccount from ALL config files.
    DST="$STASHED_OAUTH" python3 -c "
import sys, json, os

files = sys.argv[1:]
dst = os.environ['DST']

# Back up from the first file that has oauthAccount
backed_up = False
for path in files:
    with open(path) as f:
        d = json.load(f)
    if 'oauthAccount' in d and not backed_up:
        with open(dst, 'w') as f:
            json.dump(d['oauthAccount'], f, indent=2)
            f.write('\n')
        backed_up = True

# Strip oauthAccount from every config file
for path in files:
    with open(path) as f:
        d = json.load(f)
    if 'oauthAccount' not in d:
        continue
    d.pop('oauthAccount')
    with open(path + '.tmp', 'w') as f:
        json.dump(d, f, indent=2)
        f.write('\n')
    os.replace(path + '.tmp', path)

if backed_up:
    print('stashed')
" "${files_to_strip[@]}" < /dev/null
    local result=$?
    if [ $result -eq 0 ] && [ -f "$STASHED_OAUTH" ]; then
        echo "  OAuth token stashed (will restore on 'official')"
    fi
}

# Restore OAuth account into claude config when switching back to official.
# Restores into all existing config files.
restore_oauth() {
    if [ ! -f "$STASHED_OAUTH" ]; then
        return
    fi
    local files_to_restore=()
    for f in "$CLAUDE_JSON" "$CLAUDE_JSON_LEGACY"; do
        [ -f "$f" ] && files_to_restore+=("$f")
    done
    if [ ${#files_to_restore[@]} -eq 0 ]; then
        return
    fi

    BAK="$STASHED_OAUTH" python3 -c "
import sys, json, os

files = sys.argv[1:]
bak = os.environ['BAK']
with open(bak) as f:
    oauth = json.load(f)
for path in files:
    with open(path) as f:
        d = json.load(f)
    d['oauthAccount'] = oauth
    with open(path + '.tmp', 'w') as f:
        json.dump(d, f, indent=2)
        f.write('\n')
    os.replace(path + '.tmp', path)
os.remove(bak)
print('restored')
" "${files_to_restore[@]}" < /dev/null
    local result=$?
    if [ $result -eq 0 ]; then
        echo "  OAuth token restored"
    fi
}

# Save active mode
save_mode() {
    echo "$1" > "$ACTIVE_FILE"
}

# Get current mode
get_mode() {
    if [ -f "$ACTIVE_FILE" ]; then
        cat "$ACTIVE_FILE"
    else
        # Infer from settings.json
        if [ -f "$CLAUDE_SETTINGS" ] && grep -q '"apiBaseUrl"' "$CLAUDE_SETTINGS" 2>/dev/null; then
            echo "proxy"
        else
            echo "official"
        fi
    fi
}

cmd_proxy() {
    local url_arg="${1:-}" key_arg="${2:-}"

    # Apply CLI overrides and persist to config
    if [ -n "$url_arg" ]; then
        PROXY_BASE_URL="$url_arg"
        update_config "PROXY_BASE_URL" "$PROXY_BASE_URL"
    fi
    if [ -n "$key_arg" ]; then
        PROXY_API_KEY="$key_arg"
        update_config "PROXY_API_KEY" "$PROXY_API_KEY"
    fi

    validate_proxy_config "$PROXY_BASE_URL" "$PROXY_API_KEY"

    write_settings proxy
    write_env proxy
    stash_oauth
    save_mode proxy

    echo "Switched to PROXY mode"
    echo "  API base: $PROXY_BASE_URL"
    echo "  settings.json: apiBaseUrl set"
    echo ""
    echo "Run 'source ~/.config/claude-switch/env' or restart your shell to apply env vars."
}

cmd_official() {
    write_settings official
    write_env official
    restore_oauth
    save_mode official

    echo "Switched to OFFICIAL mode"
    echo "  Using Claude AI OAuth credentials"
    echo "  settings.json: apiBaseUrl removed"
    echo ""
    echo "Run 'source ~/.config/claude-switch/env' or restart your shell to apply env vars."
}

cmd_status() {
    local mode
    mode=$(get_mode)

    echo "Claude Code auth mode: $mode"
    echo ""

    if [ "$mode" = "proxy" ]; then
        echo "  API base URL: $PROXY_BASE_URL"
        if [ -n "$PROXY_API_KEY" ]; then
            echo "  API key: ${PROXY_API_KEY:0:10}..."
        else
            echo "  API key: (not set)"
        fi
        if [ -f "$STASHED_OAUTH" ]; then
            echo "  OAuth token: stashed (will restore on 'official')"
        fi
    else
        echo "  Using Claude AI OAuth"
        # Check primary config first, then legacy
        if { [ -f "$CLAUDE_JSON" ] && SRC="$CLAUDE_JSON" python3 -c "
import json, sys, os
with open(os.environ['SRC']) as f:
    d = json.load(f)
sys.exit(0 if 'oauthAccount' in d else 1)
" < /dev/null 2>/dev/null; } || { [ -f "$CLAUDE_JSON_LEGACY" ] && SRC="$CLAUDE_JSON_LEGACY" python3 -c "
import json, sys, os
with open(os.environ['SRC']) as f:
    d = json.load(f)
sys.exit(0 if 'oauthAccount' in d else 1)
" < /dev/null 2>/dev/null; }; then
            echo "  OAuth token: present"
        else
            echo "  OAuth token: not found (run 'claude' to log in)"
        fi
    fi

    echo ""
    echo "  Settings file: $CLAUDE_SETTINGS"
    if [ -f "$CLAUDE_SETTINGS" ]; then
        if grep -q '"apiBaseUrl"' "$CLAUDE_SETTINGS" 2>/dev/null; then
            echo "  apiBaseUrl: $(grep '"apiBaseUrl"' "$CLAUDE_SETTINGS" | sed 's/.*: *"\(.*\)".*/\1/')"
        else
            echo "  apiBaseUrl: (not set)"
        fi
    else
        echo "  (file not found)"
    fi

    echo ""
    echo "  ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL:-(not set)}"
    if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
        echo "  ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:0:10}..."
    else
        echo "  ANTHROPIC_API_KEY=(not set)"
    fi
}

cmd_config() {
    echo "Config file: $CONFIG_FILE"
    echo ""
    echo "Current values:"
    echo "  PROXY_BASE_URL=$PROXY_BASE_URL"
    if [ -n "$PROXY_API_KEY" ]; then
        echo "  PROXY_API_KEY=${PROXY_API_KEY:0:10}..."
    else
        echo "  PROXY_API_KEY=(not set)"
    fi
    echo ""
    echo "Edit directly: \${EDITOR:-vi} $CONFIG_FILE"
}

# Main
case "${1:-}" in
    proxy)    cmd_proxy "${2:-}" "${3:-}" ;;
    official) cmd_official ;;
    status)   cmd_status ;;
    config)   cmd_config ;;
    *)        usage ;;
esac
