#!/usr/bin/env bash
# Copy host Claude auth into the container.
# Host files are mounted read-only so originals are never at risk.
set -euo pipefail

# ~/.claude/ directory (settings.json, claude.json legacy, etc.)
if [ -d /host-claude ]; then
    echo "Copying host auth from /host-claude → /root/.claude ..."
    mkdir -p /root/.claude
    cp -a /host-claude/. /root/.claude/
else
    echo "No /host-claude mount found — using empty defaults"
    mkdir -p /root/.claude
    echo '{}' > /root/.claude/settings.json
    echo '{}' > /root/.claude/claude.json
fi

# ~/.claude.json (primary config — current Claude Code location)
if [ -f /host-claude-json ]; then
    echo "Copying host config from /host-claude-json → /root/.claude.json ..."
    cp /host-claude-json /root/.claude.json
else
    echo "No /host-claude-json mount found — creating empty /root/.claude.json"
    echo '{}' > /root/.claude.json
fi

# Pre-configure proxy env vars so they're active immediately.
# We write the config/env files directly instead of running
# `claude-switch proxy` to avoid stashing OAuth (tests need it intact).
PROXY_URL="${TEST_PROXY_URL:-http://host.docker.internal:11212/api/anthropic}"
PROXY_KEY="${TEST_PROXY_KEY:-test-key}"

mkdir -p ~/.config/claude-switch
cat > ~/.config/claude-switch/config <<EOF
PROXY_BASE_URL=$PROXY_URL
PROXY_API_KEY=$PROXY_KEY
EOF

cat > ~/.config/claude-switch/env <<EOF
# Claude Code auth — proxy mode (auto-generated by docker-entrypoint)
export ANTHROPIC_BASE_URL="$PROXY_URL"
export ANTHROPIC_API_KEY="$PROXY_KEY"
EOF

echo "proxy" > ~/.config/claude-switch/active

# Apply env vars for the current process
export ANTHROPIC_BASE_URL="$PROXY_URL"
export ANTHROPIC_API_KEY="$PROXY_KEY"

echo "Proxy pre-configured → $PROXY_URL"

exec "$@"
